DUT\Models\Commentaire:
  type: entity

  

  table: Commentaire  
  id:
    id:
      type: integer
      generator:
        strategy: auto

  fields:        
    contenu:
      type: string
      column: contenu
      nullable: false
      
    id_article:
      type: integer
      column: id_article
      nullable: false
      
    id_utilisateur:
      type: integer
      column: id_utilisateur
      nullable: false
  
