DUT\Models\Item:
  type: entity
  table: item
  
  id:
    id:
      type: integer
      generator:
        strategy: auto

  fields:
    title:
      type: string
      column: title
      nullable: false
    
    checked:
      type: boolean
      column: checked
      nullable: false
        
    
