DUT\Models\Utilisateurs:
  type: entity
  
  oneToMany:
    commentaires:
      targetEntity: Commentaire
      mappedBy: utilisateur

  table: Utilisateur
  
  id:
    id:
      type: integer
      generator:
        strategy: auto

  fields:
    mail:
      type: string
      column: mail
      nullable: false
    
    pseudo:
      type: string
      column: pseudo
      nullable: false
        
    mdp:
      type: string
      column: mdp
      nullable: false
    admin:
      type: integer
      column: admin
      nullable: false
